//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Position { get; set; }
        public Nullable<int> TeamId { get; set; }
    
        public virtual Teams Teams { get; set; }
    }
}
